const accounts_db = {
  'Checking': {
    'Chase': [
      {
        "issuer": "Chase",
        "name": "Total Checking",
        "fee": 12,
        "notes": "",
        "image": "https://download.logo.wine/logo/Chase_Bank/Chase_Bank-Logo.wine.png",
        "link": "https://www.chase.com/personal/checking/total-checking"
      },
      {
        "issuer": "Chase",
        "name": "College Checking",
        "fee": 0,
        "notes": "",
        "image": "https://download.logo.wine/logo/Chase_Bank/Chase_Bank-Logo.wine.png",
        "link": "https://www.chase.com/personal/checking/student-checking"
      }
    ],
    'Capital One': [
      {
        "issuer": "Capital One",
        "name": "360 Checking",
        "fee": 0,
        "notes": "",
        "image": "https://logos-world.net/wp-content/uploads/2021/04/Capital-One-Logo.png",
        "link": "https://www.capitalone.com/bank/checking-accounts/online-checking-account/"
      }
    ],
    'Bank of America': [
      {
        "issuer": "Bank of America",
        "name": "Advantage Banking",
        "fee": 12,
        "notes": "",
        "image": "https://1000logos.net/wp-content/uploads/2016/10/Bank-of-America-logo.png",
        "link": "https://www.bankofamerica.com/deposits/checking/advantage-banking/"
      }
    ],
    'Wells Fargo': [
      {
        "issuer": "Wells Fargo",
        "name": "Everyday Checking",
        "fee": 10,
        "notes": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Wells_Fargo_Bank.svg/1024px-Wells_Fargo_Bank.svg.png",
        "link": "https://www.wellsfargo.com/checking/everyday/"
      }
    ],
    'Venmo': [
      {
        "issuer": "Other",
        "name": "Venmo",
        "fee": 0,
        "notes": "",
        "image": "https://i.pcmag.com/imagery/reviews/05Zr4cy33kGKkO4e92S3wV7-13..1602794368.png",
        "link": "https://venmo.com"
      }
    ],
    "Ally Bank": [
      {
        "issuer": "Ally Bank",
        "name": "Interest Checking",
        "fee": 0,
        "notes": "",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Ally_Bank_logo.svg/1280px-Ally_Bank_logo.svg.png",
        "link": "https://www.ally.com/bank/interest-checking-account/"
      }
    ],
    'Other': [
      {
        "issuer": "Other",
        "name": "Generic checking account",
        "fee": 0,
        "notes": "",
        "image": "https://lh3.googleusercontent.com/proxy/8ki81iCRyOu1l4rfD1JIJIIgQyh5N5Ujalsj76IEtBPT4nLF1OyoSp9gb8YBvBiZ9rAUBhOxHIUg0Ir_GnegYutIntUFfX_PH4Wloows-o-L9Lww7wVRMzxx98DDZJxTK1_w",
        "link": "https://en.wikipedia.org/wiki/Checking_account"
      }
    ]
  },
  'Savings': {
    'Chase': [
      {
        "issuer": "Chase",
        "name": "Savings",
        "fee": 60,
        "image": "https://download.logo.wine/logo/Chase_Bank/Chase_Bank-Logo.wine.png",
      }
    ],
    'Bank of America': [
      {
        "issuer": "Bank of America",
        "name": "Advantage Savings",
        "fee": 96,
        "image": "https://1000logos.net/wp-content/uploads/2016/10/Bank-of-America-logo.png",
      }
    ],
    'American Express': [
      {
        "issuer": "American Express",
        "name": "High Yield Savings",
        "fee": 0,
        "image": "https://s1.q4cdn.com/692158879/files/images/brand_imagery/American-Express-Logotype-Stacked.png",
      }
    ],
    'Ally Bank': [
      {
        "issuer": "Ally Bank",
        "name": "Online Savings",
        "fee": 0,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Ally_Bank_logo.svg/1280px-Ally_Bank_logo.svg.png",
      }
    ],
    'Discover': [
      {
        "issuer": "Discover",
        "name": "Online Savings",
        "fee": 0,
        "image": "https://1000logos.net/wp-content/uploads/2021/05/Discover-logo.png"
      }
    ],
    'Citi': [
      {
        "issuer": "Citi",
        "name": "Savings",
        "fee": 4.50,
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Citi.svg/320px-Citi.svg.png"
      }
    ],
    'Other': [
      {
        "issuer": "Other",
        "name": "Generic savings account",
        "fee": 0
      }
    ]
  },
  'Investment': {
    'Vanguard': [
      {
        "issuer": "Vanguard",
        "name": "Traditional IRA",
        "fee": 0,
        "image": "https://cdn-static.findly.com/wp-content/uploads/sites/11/2015/02/CareersSite_FeaturedImage_Home_640x480.jpg"
      },
      {
        "issuer": "Vanguard",
        "name": "Roth IRA",
        "fee": 0,
        "image": "https://cdn-static.findly.com/wp-content/uploads/sites/11/2015/02/CareersSite_FeaturedImage_Home_640x480.jpg"
      },
      {
        "issuer": "Vanguard",
        "name": "401(k)",
        "fee": 0,
        "image": "https://cdn-static.findly.com/wp-content/uploads/sites/11/2015/02/CareersSite_FeaturedImage_Home_640x480.jpg"
      },
      {
        "issuer": "Vanguard",
        "name": "Individual Brokerage",
        "fee": 0,
        "image": "https://cdn-static.findly.com/wp-content/uploads/sites/11/2015/02/CareersSite_FeaturedImage_Home_640x480.jpg"
      },
    ],
    'Fidelity': [
      {
        "issuer": "Fidelity",
        "name": "Traditional IRA",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/02/Fidelity-Symbol.jpg"
      },
      {
        "issuer": "Fidelity",
        "name": "Roth IRA",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/02/Fidelity-Symbol.jpg"
      },
      {
        "issuer": "Fidelity",
        "name": "401(k)",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/02/Fidelity-Symbol.jpg"
      },
      {
        "issuer": "Fidelity",
        "name": "Individual Brokerage",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/02/Fidelity-Symbol.jpg"
      },
    ],
    'Charles Schwab': [
      {
        "issuer": "Charles Schwab",
        "name": "Traditional IRA",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/03/Charles-Schwab-Emblem.png"
      },
      {
        "issuer": "Charles Schwab",
        "name": "Roth IRA",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/03/Charles-Schwab-Emblem.png"
      },
      {
        "issuer": "Charles Schwab",
        "name": "401(k)",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/03/Charles-Schwab-Emblem.png"
      },
      {
        "issuer": "Charles Schwab",
        "name": "One Brokerage",
        "fee": 0,
        "image": "https://logos-world.net/wp-content/uploads/2021/03/Charles-Schwab-Emblem.png"
      },
    ],
    'Other': [
      {
        "issuer": "Other",
        "name": "Generic brokerage account",
        "fee": 0
      }
    ]
  },
  'Loan': {
    'Other': [
      {
        "issuer": "Other",
        "name": "Auto loan"
      },
      {
        "issuer": "Other",
        "name": "Mortgage"
      },
      {
        "issuer": "Other",
        "name": "Student loan"
      },
      {
        "issuer": "Other",
        "name": "Personal loan"
      },
      {
        "issuer": "Other",
        "name": "Generic loan"
      }
    ]
  },
  'Other': {
    'Other': [
      {
        "issuer": "Other",
        "name": "Generic account"
      }
    ]
  },
  'Credit Card': {
    "Discover It": [
      {
        "issuer": "Discover It",
        "name": "Student Cash Back",
        "fee": 0,
        "type": "Cash back",
        "credit": 300,
        "restaurants": 0.01,
        "gas": 0.01,
        "groceries": 0.01,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "Yes",
        "tsa": "No",
        "insurance": "No",
        "builder": "Yes",
        "notes": "5% rotating cash back",
        "image": "https://m.foolcdn.com/media/affiliates/credit-card-art/discover-it-student-cash-back_5mNPw7i.png",
        "link": "https://www.discover.com/credit-cards/student/it-card.html"
      },
      {
        "issuer": "Discover It",
        "name": "Chrome for Students",
        "fee": 0,
        "type": "Cash back",
        "credit": 300,
        "restaurants": 0.02,
        "gas": 0.02,
        "groceries": 0.01,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "Yes",
        "notes": "",
        "image": "https://cdn.wallethub.com/common/product/images/creditcards/500/discover-it-chrome-for-students-credit-card-1003548c.png",
        "link": "https://www.discover.com/credit-cards/student/chrome-card.html"
      },
      {
        "issuer": "Discover It",
        "name": "Miles",
        "fee": 0,
        "type": "Travel",
        "credit": 670,
        "restaurants": 1.5,
        "gas": 1.5,
        "groceries": 1.5,
        "travel": 1.5,
        "entertainment": 1.5,
        "online shopping": 1.5,
        "other": 1.5,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.creditcards.com/ext/cdn.prodstatic.com/shared/images/cards/336x211/7c8fe9c0-bb9c-11ea-bf12-c7437d5726b0.png",
        "link": "https://www.discover.com/credit-cards/travel/"
      }
    ],
    "Chase": [
      {
        "issuer": "Chase",
        "name": "Freedom Flex",
        "fee": 0,
        "type": "Cash back",
        "credit": 690,
        "restaurants": 0.03,
        "gas": 0.01,
        "groceries": 0.01,
        "travel": 0.05,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "Yes",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "5% on travel is only if booked through Chase's portal",
        "image": "https://creditcards.chase.com/K-Marketplace/images/modals/freedom_cal_freedom_flex_card.png",
        "link": "https://creditcards.chase.com/cash-back-credit-cards/freedom/flex"
      },
      {
        "issuer": "Chase",
        "name": "Freedom Unlimited",
        "fee": 0,
        "type": "Cash back",
        "credit": 700,
        "restaurants": 0.03,
        "gas": 0.015,
        "groceries": 0.015,
        "travel": 0.05,
        "entertainment": 0.015,
        "online shopping": 0.015,
        "other": 0.015,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "5% on travel is only if booked through Chase's portal",
        "image": "https://creditcards.chase.com/K-Marketplace/images/cardart/freedom_unlimited_card.png",
        "link": "https://creditcards.chase.com/cash-back-credit-cards/freedom/unlimited"
      },
      {
        "issuer": "Chase",
        "name": "Freedom Student",
        "fee": 0,
        "type": "Cash back",
        "credit": 300,
        "restaurants": 0.01,
        "gas": 0.01,
        "groceries": 0.01,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "Yes",
        "notes": "",
        "image": "https://creditcards.chase.com/K-Marketplace/images/cardart/freedom_student_card.png",
        "link": "https://creditcards.chase.com/cash-back-credit-cards/freedom/student"
      },
      {
        "issuer": "Chase",
        "name": "Sapphire Preferred",
        "fee": 95,
        "type": "Travel",
        "credit": 760,
        "restaurants": 3,
        "gas": 1,
        "groceries": 1,
        "travel": 5,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "Yes",
        "builder": "No",
        "notes": "5x on travel is only if booked through Chase",
        "image": "https://creditcards.chase.com/K-Marketplace/images/cardart/sapphire_preferred_card.png",
        "link": "https://creditcards.chase.com/rewards-credit-cards/sapphire/preferred"
      },
      {
        "issuer": "Chase",
        "name": "Sapphire Reserve",
        "fee": 550,
        "type": "Travel",
        "credit": 760,
        "restaurants": 3,
        "gas": 1,
        "groceries": 1,
        "travel": 3,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "Yes",
        "insurance": "Yes",
        "builder": "No",
        "notes": "$300 annual travel credit",
        "image": "https://creditcards.chase.com/K-Marketplace/images/cardart/sapphire_reserve_card.png",
        "link": "https://creditcards.chase.com/rewards-credit-cards/sapphire/reserve"
      },
      {
        "issuer": "Chase",
        "name": "Amazon Prime Rewards",
        "fee": 0,
        "type": "Cash back",
        "credit": 750,
        "restaurants": 0.02,
        "gas": 0.02,
        "groceries": 0.01,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.05,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "Requires Prime membership + 5% cash back at Whole Foods as well",
        "image": "https://creditcards.chase.com/K-Marketplace/images/cardart/amazon_card.png",
        "link": "https://www.amazon.com/gp/cobrandcard?&plattr=ChaseMS"
      }
    ],
    "Citi": [
      {
        "issuer": "Citi",
        "name": "Double Cash",
        "fee": 0,
        "type": "Cash back",
        "credit": 760,
        "restaurants": 0.02,
        "gas": 0.02,
        "groceries": 0.02,
        "travel": 0.02,
        "entertainment": 0.02,
        "online shopping": 0.02,
        "other": 0.02,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.citi.com/CRD/images/card_no_reflection/citi-double-cash-credit-card.jpg",
        "link": "https://www.citi.com/credit-cards/citi-double-cash-credit-card"
      },
      {
        "issuer": "Citi",
        "name": "Premier",
        "fee": 95,
        "type": "Travel",
        "credit": 760,
        "restaurants": 3,
        "gas": 3,
        "groceries": 3,
        "travel": 3,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.citi.com/CRD/images/citi-premier/citi-premier_222x140.png",
        "link": "https://www.citi.com/credit-cards/citi-premier-credit-card"
      },
      {
        "issuer": "Citi",
        "name": "Custom Cash",
        "fee": 0,
        "type": "Cash back",
        "credit": 760,
        "restaurants": 0.01,
        "gas": 0.01,
        "groceries": 0.01,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "Yes",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "5% cash back in top spend category",
        "image": "https://mms.businesswire.com/media/20210610005221/en/884310/5/Custom_Cash.jpg",
        "link": "https://www.citi.com/credit-cards/citi-custom-cash-credit-card"
      },
      {
        "issuer": "Citi",
        "name": "Rewards+",
        "fee": 0,
        "type": "Travel",
        "credit": 760,
        "restaurants": 1,
        "gas": 2,
        "groceries": 2,
        "travel": 1,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "Purchases round points up to the nearest 10",
        "image": "https://www.citi.com/CRD/images/citi-rewards-plus/citi-rewards-plus_222x140.png",
        "link": "https://www.citi.com/credit-cards/citi-rewards-plus-credit-card"
      },
      {
        "issuer": "Citi",
        "name": "AAdvantage MileUp",
        "fee": 0,
        "type": "Travel",
        "credit": 700,
        "restaurants": 1,
        "gas": 1,
        "groceries": 2,
        "travel": 2,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "2x on travel is only for American Airlines purchases",
        "image": "https://www.creditcards.com/ext/cdn.prodstatic.com/shared/images/cards/336x211/72fe5080-fb22-11e9-9794-5d95042ca5c0.png",
        "link": "https://creditcards.aa.com/citi-mileup-card-american-airlines-direct/"
      },
      {
        "issuer": "Citi",
        "name": "AAdvantage Platinum Select",
        "fee": 99,
        "type": "Travel",
        "credit": 700,
        "restaurants": 2,
        "gas": 2,
        "groceries": 1,
        "travel": 2,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "Yes",
        "builder": "No",
        "notes": "Free checked bag + priority boarding",
        "image": "https://creditcards.aa.com/wp-content/uploads/2018/07/platinum_card-hires.png",
        "link": "https://creditcards.aa.com/citi-platinum-card-american-airlines-wand/?utm_medium=referral&utm_source=aa&utm_campaign=ccpage"
      }
    ],
    "Capital One": [
      {
        "issuer": "Capital One",
        "name": "VentureOne",
        "fee": 0,
        "type": "Travel",
        "credit": 760,
        "restaurants": 1.25,
        "gas": 1.25,
        "groceries": 1.25,
        "travel": 1.25,
        "entertainment": 1.25,
        "online shopping": 1.25,
        "other": 1.25,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://ecm.capitalone.com/WCM/card/products/ventureone-card-art/tablet.png",
        "link": "https://www.capitalone.com/credit-cards/ventureone/"
      },
      {
        "issuer": "Capital One",
        "name": "Venture",
        "fee": 95,
        "type": "Travel",
        "credit": 760,
        "restaurants": 2,
        "gas": 2,
        "groceries": 2,
        "travel": 2,
        "entertainment": 2,
        "online shopping": 2,
        "other": 2,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "Yes",
        "insurance": "Yes",
        "builder": "No",
        "notes": "",
        "image": "https://ecm.capitalone.com/WCM/card/products/venture-card-art/tablet.png",
        "link": "https://www.capitalone.com/credit-cards/venture/"
      },
      {
        "issuer": "Capital One",
        "name": "SavorOne",
        "fee": 0,
        "type": "Cash back",
        "credit": 760,
        "restaurants": 0.03,
        "gas": 0.01,
        "groceries": 0.03,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://ecm.capitalone.com/WCM/card/products/savorone-card-art/tablet.png",
        "link": "https://www.capitalone.com/credit-cards/savorone-dining-rewards/"
      },
      {
        "issuer": "Capital One",
        "name": "Savor",
        "fee": 95,
        "type": "Cash back",
        "credit": 760,
        "restaurants": 0.04,
        "gas": 0.01,
        "groceries": 0.03,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://ecm.capitalone.com/WCM/card/products/savor-card-art/tablet.png",
        "link": "https://www.capitalone.com/credit-cards/savor-dining-rewards/"
      },
      {
        "issuer": "Capital One",
        "name": "SavorOne for Students",
        "fee": 0,
        "type": "Cash back",
        "credit": 580,
        "restaurants": 0.03,
        "gas": 0.01,
        "groceries": 0.03,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "Yes",
        "notes": "",
        "image": "https://ecm.capitalone.com/WCM/card/products/savorone-card-art.png",
        "link": "https://www.capitalone.com/credit-cards/savorone-student/"
      },
      {
        "issuer": "Capital One",
        "name": "Quicksilver",
        "fee": 0,
        "type": "Cash back",
        "credit": 760,
        "restaurants": 0.015,
        "gas": 0.015,
        "groceries": 0.015,
        "travel": 0.015,
        "entertainment": 0.015,
        "online shopping": 0.015,
        "other": 0.015,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.creditcards.com/ext/cdn.prodstatic.com/shared/images/cards/336x211/capital-one-quicksilver-cash-rewards-credit-card-041217.png",
        "link": "https://www.capitalone.com/credit-cards/quicksilver/"
      },
      {
        "issuer": "Capital One",
        "name": "Quicksilver Student",
        "fee": 0,
        "type": "Cash back",
        "credit": 300,
        "restaurants": 0.015,
        "gas": 0.015,
        "groceries": 0.015,
        "travel": 0.015,
        "entertainment": 0.015,
        "online shopping": 0.015,
        "other": 0.015,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.creditcards.com/ext/cdn.prodstatic.com/shared/images/cards/336x211/f583a350-0063-11ec-97b1-37a1bb7c2537.png",
        "link": "https://www.capitalone.com/credit-cards/quicksilver-student/"
      }
    ],
    "American Express": [
      {
        "issuer": "American Express",
        "name": "Blue Cash Everyday",
        "fee": 0,
        "type": "Cash back",
        "credit": 700,
        "restaurants": 0.01,
        "gas": 0.02,
        "groceries": 0.03,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/blue-cash-everyday.png",
        "link": "https://www.americanexpress.com/us/credit-cards/card/blue-cash-everyday/"
      },
      {
        "issuer": "American Express",
        "name": "Blue Cash Preferred",
        "fee": 95,
        "type": "Cash back",
        "credit": 700,
        "restaurants": 0.01,
        "gas": 0.03,
        "groceries": 0.06,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "6% cash back is only up to $6k in spend",
        "image": "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/blue-cash-preferred.png",
        "link": "https://www.americanexpress.com/us/credit-cards/card/blue-cash-preferred/"
      },
      {
        "issuer": "American Express",
        "name": "Green Card",
        "fee": 150,
        "type": "Travel",
        "credit": 760,
        "restaurants": 3,
        "gas": 1,
        "groceries": 1,
        "travel": 3,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "Yes",
        "builder": "No",
        "notes": "",
        "image": "https://cdn.wallethub.com/common/product/images/creditcards/500/american-express-green-card-1340467c.jpg",
        "link": "https://www.americanexpress.com/us/credit-cards/card/green/"
      },
      {
        "issuer": "American Express",
        "name": "Gold Card",
        "fee": 250,
        "type": "Travel",
        "credit": 760,
        "restaurants": 4,
        "gas": 1,
        "groceries": 4,
        "travel": 3,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "Yes",
        "builder": "No",
        "notes": "$120 Uber cash",
        "image": "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/gold-card.png",
        "link": "https://www.americanexpress.com/us/credit-cards/card/gold-card/"
      },
      {
        "issuer": "American Express",
        "name": "Platinum Card",
        "fee": 695,
        "type": "Travel",
        "credit": 760,
        "restaurants": 1,
        "gas": 1,
        "groceries": 1,
        "travel": 5,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "Yes",
        "insurance": "Yes",
        "builder": "No",
        "notes": "$200 Uber cash + $200 travel credit + other benefits",
        "image": "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/OneSite/category/cardarts/platinum-card.png",
        "link": "https://www.americanexpress.com/us/credit-cards/card/platinum/"
      }
    ],
    "Bank of America": [
      {
        "issuer": "Bank of America",
        "name": "Travel Rewards",
        "fee": 0,
        "type": "Travel",
        "credit": 750,
        "restaurants": 1.5,
        "gas": 1.5,
        "groceries": 1.5,
        "travel": 1.5,
        "entertainment": 1.5,
        "online shopping": 1.5,
        "other": 1.5,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8blm_trvsigcm_v_250x158.png",
        "link": "https://www.bankofamerica.com/credit-cards/products/travel-rewards-credit-card/"
      },
      {
        "issuer": "Bank of America",
        "name": "Customized Cash Rewards",
        "fee": 0,
        "type": "Cash back",
        "credit": 750,
        "restaurants": 0.01,
        "gas": 0.01,
        "groceries": 0.02,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "Yes",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "3% cash back on user-selected category",
        "image": "https://www.nerdwallet.com/cdn/images/marketplace/credit_cards/56683306-5399-4ad5-873f-925ac4b61e9a/4abab28bcdaf1889a87cb0d20d72f1ca670e86145d1da744a1ffe2797b117174.jpg",
        "link": "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card/"
      },
      {
        "issuer": "Bank of America",
        "name": "Unlimited Cash Rewards",
        "fee": 0,
        "type": "Cash back",
        "credit": 750,
        "restaurants": 0.015,
        "gas": 0.015,
        "groceries": 0.015,
        "travel": 0.015,
        "entertainment": 0.015,
        "online shopping": 0.015,
        "other": 0.015,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8cty_cshsigcm_v_250x157.png",
        "link": "https://www.bankofamerica.com/credit-cards/products/unlimited-cash-back-credit-card/"
      },
      {
        "issuer": "Bank of America",
        "name": "Premium Rewards",
        "fee": 95,
        "type": "Travel",
        "credit": 750,
        "restaurants": 2,
        "gas": 1.5,
        "groceries": 2,
        "travel": 2,
        "entertainment": 1.5,
        "online shopping": 1.5,
        "other": 1.5,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "Yes",
        "insurance": "Yes",
        "builder": "No",
        "notes": "2x on groceries is only until end of 2021",
        "image": "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/Approved_PCM/8cal_prmsigcm_v_250x158.png",
        "link": "https://www.bankofamerica.com/credit-cards/products/premium-rewards-credit-card/"
      },
      {
        "issuer": "Bank of America",
        "name": "Travel Rewards for Students",
        "fee": 0,
        "type": "Travel",
        "credit": 300,
        "restaurants": 1.5,
        "gas": 1.5,
        "groceries": 1.5,
        "travel": 1.5,
        "entertainment": 1.5,
        "online shopping": 1.5,
        "other": 1.5,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "Yes",
        "notes": "",
        "image": "https://www.forbes.com/advisor/wp-content/uploads/2020/02/8blm_trvsigcm_v_250x158-1.png",
        "link": "https://www.bankofamerica.com/credit-cards/products/travel-rewards-credit-card/"
      }
    ],
    "Visa": [
      {
        "issuer": "Visa",
        "name": "Petal 2",
        "fee": 0,
        "type": "Cash back",
        "credit": 300,
        "restaurants": 0.01,
        "gas": 0.01,
        "groceries": 0.01,
        "travel": 0.01,
        "entertainment": 0.01,
        "online shopping": 0.01,
        "other": 0.01,
        "conversion": 1,
        "rotating/custom": "Yes",
        "tsa": "No",
        "insurance": "No",
        "builder": "Yes",
        "notes": "1.5% cash back after 12 months of payments + higher cash back at select merchants",
        "image": "https://ck-content.imgix.net/pcm/content/127176e9afc411dce2e8-Petal-2-Card_Art__1_.png",
        "link": "https://www.petalcard.com/petal-2"
      }
    ],
    "Wells Fargo": [
      {
        "issuer": "Wells Fargo",
        "name": "Active Cash",
        "fee": 0,
        "type": "Cash back",
        "credit": 700,
        "restaurants": 0.02,
        "gas": 0.02,
        "groceries": 0.02,
        "travel": 0.02,
        "entertainment": 0.02,
        "online shopping": 0.02,
        "other": 0.02,
        "conversion": 1,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://www.creditcards.com/ext/cdn.prodstatic.com/shared/images/cards/336x211/04601840-e56b-11eb-99d8-ddd3faec9ad4.png",
        "link": "https://creditcards.wellsfargo.com/active-cash-credit-card/"
      }
    ],
    "Barclays": [
      {
        "issuer": "Barclays",
        "name": "AAdvantage Aviator",
        "fee": 0,
        "type": "Travel",
        "credit": 700,
        "restaurants": 0.5,
        "gas": 0.5,
        "groceries": 0.5,
        "travel": 1,
        "entertainment": 0.5,
        "online shopping": 0.5,
        "other": 0.5,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "1x on travel is only for American Airlines purchases",
        "image": "https://creditcards.aa.com/wp-content/uploads/2019/01/aviator_mastercard.png",
        "link": "https://creditcards.aa.com/barclay-credit-card-aviator-american-airlines-aadvantage/"
      },
      {
        "issuer": "Barclays",
        "name": "AAdvantage Aviator Red",
        "fee": 99,
        "type": "Travel",
        "credit": 700,
        "restaurants": 1,
        "gas": 1,
        "groceries": 1,
        "travel": 2,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "Yes",
        "builder": "No",
        "notes": "Free checked bag + priority boarding",
        "image": "https://cards.barclaycardus.com/content/dam/bcuspublic/card-plastic/card-front/AA2_card_rRGB_AviatorRed_WE_359x246_4074_072418.png",
        "link": "https://cards.barclaycardus.com/banking/cards/aadvantage-aviator-red-world-elite-mastercard/"
      },
      {
        "issuer": "Barclays",
        "name": "AAdvantage Aviator Silver",
        "fee": 195,
        "type": "Travel",
        "credit": 700,
        "restaurants": 1,
        "gas": 1,
        "groceries": 1,
        "travel": 3,
        "entertainment": 1,
        "online shopping": 1,
        "other": 1,
        "conversion": 0.01,
        "rotating/custom": "No",
        "tsa": "Yes",
        "insurance": "Yes",
        "builder": "No",
        "notes": "Free checked bag + priority boarding + $25 inflight food credit + $50 inflight WiFi credit",
        "image": "https://creditcards.aa.com/wp-content/uploads/2019/01/aviator_silver.png",
        "link": "https://creditcards.aa.com/barclay-credit-card-aviator-silver-american-airlines-aadvantage/"
      }
    ],
    "Other": [
      {
        "issuer": "Other",
        "name": "Generic credit card",
        "fee": 0,
        "type": "Cash back",
        "credit": 300,
        "restaurants": 0,
        "gas": 0,
        "groceries": 0,
        "travel": 0,
        "entertainment": 0,
        "online shopping": 0,
        "other": 0,
        "conversion": 0,
        "rotating/custom": "No",
        "tsa": "No",
        "insurance": "No",
        "builder": "No",
        "notes": "",
        "image": "https://slashgear.com/wp-content/uploads/2017/10/mastercard_main.jpg",
        "link": "https://en.wikipedia.org/wiki/Credit_card"
      }
    ]
  }
};

export default accounts_db;
